Repository blockchaintp/chronicle-examples, pull requests merged in 2022-10, with the labels that each got.

#2 fix/dont require buildkit
  .pre-commit-config.yaml
  Makefile
  docker/chronicle.dockerfile
Labels: size/M

#4 feature/stl builds
  .tool-versions
  Makefile
  README.md
  docker/chronicle.dockerfile
  docker/docker-compose.yaml
  docker/stl-domain.yaml
Labels: size/L

#5 fix/reorganize
  .gitignore
  Makefile
  README.md
  docker/chronicle.dockerfile
  domains/artworld/domain.yaml
  domains/artworld/guide.md
  domains/evidence/domain.yaml
  domains/evidence/guide.md
Labels: size/S

#7 docs: update README.md to reference docs and prereqs
  README.md
Labels: size/M

#9 fix(docker): allow easy override of chronicle-builder image
  Makefile
  docker/chronicle.dockerfile
  docker/docker-compose.yaml
Labels: size/S

#10 Airworthiness
  domains/airworthiness/domain.yaml
  domains/airworthiness/guide.md
  domains/artworld/guide.md
  domains/evidence/guide.md
Labels: size/L

#11 feat: rename airworthiness to manufacturing and extend guide
  README.md
  domains/airworthiness/guide.md
  domains/artworld/guide.md
  domains/evidence/guide.md
  domains/manufacturing/diagrams/ItemCertified.png
  domains/manufacturing/diagrams/ItemManufactured.png
  domains/manufacturing/domain.yaml
  domains/manufacturing/guide.md
Labels: size/XXL

#12 docs: add docker compose to pre-reqs and fix manufacturing guide mark…
  README.md
  domains/manufacturing/guide.md
Labels: size/XS

#14 docs: update manu guide and README
  README.md
  domains/manufacturing/guide.md
Labels: size/L

#15 docs: copy edit guides
  domains/manufacturing/guide.md
Labels: size/S
